### ISSUE TITLE
不懂前端，这个是什么错呢

### ISSUE THREAD

**Issue by FFFro** [bosens-China/github-clone#1]
npm ERR! code E404
npm ERR! 404 Not Found: @boses/breeze-clone@latest

**Comment by bosens-China** [comment]
抱歉抱歉描述文件的内容输入错误了，请执行
npm i&nbsp;@boses/github-clone -g
或者
yarn global add&nbsp;@boses/github-clone


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bosens-China/github-clone"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月21日(星期四) 下午2:56
收件人:&nbsp;"bosens-China/github-clone"<github-clone@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[bosens-China/github-clone] 不懂前端，这个是什么错呢 (#1)





 
npm ERR! code E404
 npm ERR! 404 Not Found: @boses/breeze-clone@latest

**Comment by bosens-China** [comment]
发布这个时候遇到一些问题，导致文件没上传上去，尴尬，你稍微重试一下，如果有问题可以再联系我


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bosens-China/github-clone"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月21日(星期四) 下午2:56
收件人:&nbsp;"bosens-China/github-clone"<github-clone@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[bosens-China/github-clone] 不懂前端，这个是什么错呢 (#1)





 
npm ERR! code E404
 npm ERR! 404 Not Found: @boses/breeze-clone@latest

**Comment by bosens-China** [comment]
抱歉，描述文件写的地址有问题
``` sh
npm i -g @boses/github-clone
# or
yarn global add @boses/github-clone
```
安装的模块是 **@boses/github-clone**，刚才测试了一下已经没问题了

**Comment by FFFro** [comment]
g clone https://github.com/elastic/elasticsearch.git  这个半天没反应，你试下能拉下来么

**Comment by bosens-China** [comment]
我试下一下，拉取没什么问题，不过就是文件太大了，拉取过程中没输出信息吗， 必须拉取的进度之类的
