### ISSUE TITLE
推荐使用我们的pigcha加速器，有git加速功能，地址pigcha.com

### ISSUE THREAD

**Issue by pigpigchacha** [bosens-China/github-clone#2]
如题，可在托盘菜单进行勾选git代理，详细使用：https://github.com/pigpigchacha/GitProxy

**Comment by kari-Key7** [comment]
pigcha跑路了。非常好用的网络🪜，用了好多年了，稳定的一批
https://zli2b.wgy.life/auth/register?code=q3sk
